### ISSUE TITLE
Investigate XMPP Multiuser

### ISSUE THREAD

**Issue by olabini** [coyim/coyim#271]

**Comment by juniorz** [comment]
Related XEP: https://xmpp.org/extensions/xep-0045.html

**Comment by ioerror** [comment]
It would be nice to have support for a MUC - I just had to defect from using coy and use Gajim to join a MUC. It was a sad experience but was required for some work. We're using a trusted server for a small group - where everyone sees plaintext almost instantly because the group is size n=~6. I'd prefer it was totally encrypted and the server couldn't see any plaintext, of course.

An idea might be to use ADD_ONION to make a basic XMPP MUC that is run inside of coy itself, shared with a small number of users and extremely simple. Not quite server-free but would be a cute hack that could work very easily. Later, adding crypto on top would be easy if everyone is using a client like coy where they'll upgrade into better crypto...

**Comment by olabini** [comment]
Well actually, this specific issue has nothing to do with adding crypto on top of MUC. And as you know, mpotr solutions are a bit tricky so far. That said, the basic feature of multi user chat is something we will need to have, of course.

**Comment by ioerror** [comment]
On 3/31/16, Ola Bini <notifications@github.com> wrote:
> Well actually, this specific issue has nothing to do with adding crypto on
> top of MUC. And as you know, mpotr solutions are a bit tricky so far. That
> said, the basic feature of multi user chat is something we will need to
> have, of course.

Sure - the main concern with MUC is that it "isn't encrypted" or it
goes to an unsafe server, so TLS or .onion link crypto isn't helping a
user with a compromised server. I was mostly just thinking of how we
get from no MUC to a useful MUC or to even an interesting MUC where
e2e crypto can then be added. Sorry for the derail!

**Comment by nllz** [comment]
Is there any progress on MUC (aka jabberrooms)? Am using it a lot at IETF meetings, would be great if this would be supported by CoyIM.

**Comment by xavler23** [comment]
Any progress on this? is it working? Can i add MUC rooms to my coyim?  i have the latest from Ubuntu repo's 18.04

**Comment by olabini** [comment]
Hi. No, at the moment there hasn't been much progress. The work is not currently actively worked on, and the work-in-progress has not been released yet. Sorry about that.

**Comment by olabiniV2** [comment]
We are now releasing a version of Coy with MUC support. I would say we have investigated it fully.
