### ISSUE TITLE
Audit CoyIM

### ISSUE THREAD

**Issue by cubi7** [coyim/coyim#297]
As the website says

> CoyIM is currently under active development. There have been no security audits of the code, and you should currently not use this for anything sensitive.

Should an audit be considered sooner rather than later?

**Comment by cubi7** [comment]
Perhaps it is worth reaching out to [elttam](https://www.elttam.com.au/) who are / were in the process of auditing chat clients listed under EFF scorecard, giving each 24hours of time - [example](https://www.elttam.com.au/blog/a-review-of-the-eff-secure-messaging-scorecard-pt1/)

**Comment by olabini** [comment]
Thanks for the feedback. After some conversations with the @subgraph people, we reached the decision that it's a bit early to do an audit. There are several reasons for this - most importantly that it's a new code base and we're still making fairly significant changes to it. It's also complicated by the fact that there are really three different things that will need auditing - the gotk3 integration with GTK (which is the only place that uses native integration, and thus the likeliest place for RCE and other bad things), the OTR3 implementation of OTR, and CoyIM itself.

Auditing OTR3 right now is likely not the right choice, since we are actively working on OTR version 4, and will want to integrate that with the OTR3 library as soon as possible - this will also lead to significant changes.

We are definitely committed to auditing all of these things - including paying for in depth audits. However, my guess is we will start looking at this in 6 months or something like that.

**Comment by cubi7** [comment]
I just discovered another option for when the time comes to do an audit

https://blog.mozilla.org/blog/2016/06/09/help-make-open-source-secure/

**Comment by olabiniV2** [comment]
We have now done an audit of otr3 - the results of this will be published soon. Auditing of the other parts will probably have to wait.
