### ISSUE TITLE
Design a pleasant experience for file transfer

### ISSUE THREAD

**Issue by olabini** [coyim/coyim#384]
This is part of properly implementing file transfer.

In #18 we are tracking several different issues that are required to implement file transfer. Most of the intricacies of these methods should be hidden - but we need to expose in the user interface sending and receiving of files and folders, both encrypted and non-encrypted, and communicate this is in a nice and non-intrusive way.

**Comment by sammcj** [comment]
I'd agree - warn users before sending a file without OTR enabled.

**Comment by tdruiva** [comment]
User test:
Developer that have used other IM before

Send file 
  - From peers list, opened dialog conversation and cliked into "Send file"
  - info bar shows that is sending, what is like other apps
  - I asked if user would like to change something and them feedback was about when you are receiving a file. When popup dialog and ask to save, does not show if what you are receiving is from a verified contact or not. They said that will fill more comfortable if they are receiving a file from someone verified
  - user said that opened dialog conversation to send file because saw this option before, when was sending message also said that normally does not use the right click to open options. Would like to have an icon to send file from peers list, to have access directly to it

**Comment by claucece** [comment]
Thanks so much @tdruiva for this!! 
I'll look at it and change the ui according to the feedback.. thanks so much!

**Comment by olabiniV2** [comment]
All of the UI things have now been sorted out with the final commit.
