### ISSUE TITLE
Failing tests when building the debian package

### ISSUE THREAD

**Issue by varac** [coyim/coyim#484]
I'm using `git-buildpackage on my debian branch (gbp buildpackage --git-ignore-branch --git-builder="dpkg-buildpackage -rfakeroot -us -uc" --git-no-pristine-tar --git-upstream-tree=debian)` to build the package, but some tests fail, see [gbp log](https://github.com/coyim/coyim/files/1651697/gbp.log) for the whole log.

**Comment by olabini** [comment]
So, there are a few different problems here:
- This build seems to run the tests inside of vendor. That shouldn't happen, and it will fail because the vendor directory doesn't contain necessary files for making the tests pass
- Most of the failing tests are trying to read things from the file system, and it seems they can't. For example, the tests in config/importer/adium_test.go is using data in config/importer/adium_test_data - but for some reason it doesn't seem to be able to find it. We haven't seen that before, either locally or on our build servers, so I'm not sure how to debug it.

**Comment by olabini** [comment]
Refer to #505 for discussion - it seems Debian build is working now.
