### ISSUE TITLE
REQUEST: iOS version

### ISSUE THREAD

**Issue by SiNaPsEr0x** [coyim/coyim#492]
thanks for ASAP

**Comment by olabini** [comment]
Hi, thanks for the request. Sadly mobile phone versions of CoyIM isn't really on the map - it doesn't match our security requirements.

**Comment by SiNaPsEr0x** [comment]
thanks for the answers.... but there is other method offline AppStore.. like appdb.cc or hockeyapp

**Comment by olabini** [comment]
Sorry, I'm not sure I understand. The appstore isn't the reason. The reason is that CoyIM is aimed to be a high security instant messaging application. That simply is not possible on mobile phones.
Further, technically it's also not something that would work - our application has integration with Tor and many other features that simply wouldn't translate well to mobile.

**Comment by SiNaPsEr0x** [comment]
there is ChatSecure is similar app... from this is possible

**Comment by olabini** [comment]
I'm sorry, I'm not sure what your goal in this discussion is. I'm not going to repeat myself. ChatSecure's method of using Tor is possible, yes - but it causes a lot of problems. And once again, the Tor integration is just one of a large amount of reasons.
