### ISSUE TITLE
Create Windows installer

### ISSUE THREAD

**Issue by olabini** [coyim/coyim#522]
It would nice to have an installer for the Windows build - we can use https://nsis.sourceforge.io/Main_Page for this.

**Comment by olabiniV2** [comment]
There seems to exists at least 3 different tools that might be possible to use. `msitools`, `nsis` and `Inno Setup`. Of these, `nsis` is the only one available for msys2. I'm not a 100% clear but it seems `msitools` is actually something that runs in a Linux system for building MSIs. It would be possible for us to use `Inno Setup` since it's available in Chocolaty (a package manager for Windows, which Travis and Github Actions both support, I seem to remember). You can install it on windows simply doing `choco install InnoSetup`

For now, my suggestion is that we investigate NSIS first, as a solution to this issue.

**Comment by olabiniV2** [comment]
It seems `msitools` doesn't support creating an installer UI, something that we definitely would want.

**Comment by olabiniV2** [comment]
We could likely use something like this: https://nsis.sourceforge.io/Sample_installation_script_for_an_application as inspiration for our installer.

**Comment by olabiniV2** [comment]
This is done. We have a basic NSIS installer which publishes automatically just as the other releases.
