### ISSUE TITLE
Debian Buster

### ISSUE THREAD

**Issue by toxub23** [coyim/coyim#533]
It would be nice to put the latest version CoyIM in the Debian Buster branch.

**Comment by claucece** [comment]
Hey!

Thanks for the issue!

Please, note that it has already been discussed on issue #527 

The coyim maintainer in Debian (@satta ) has said that they quite far into the hard freeze for Debian buster, which means that bug fixes must be backported to the exact version that is currently in buster (0.3.8). The proposal for the moment is:

```
* I will finish packaging 0.3.11 including its dependencies for Debian (pending checks whether updating things like gotk3 might break anything else)
* Once buster-backports is open and the 0.3.11 stuff is in bullseye-testing, I will prepare a backport for buster, which hopefully can go into Whonix -- getting 0.3.11 into buster now is unlikely, I have just read a reply about an unrelated proposed update with way less dependencies and changes which stated that it's not targeted enough
* I will upload @claucece's patch fixing the crash and file a new bug about that. The existing bug #927290 (describing the apparent freeze during account creation) will stay open until 0.3.11 is uploaded since the new version seems to be the only practical option for fixing it.
```

Thanks!

**Comment by satta** [comment]
Unfortunately, CoyIM has not made it into buster at all because it had various bugs that could not be fixed within the constraints of the freeze (i.e. without updating to the latest version, which would have introduced too many new dependencies). 
I will try to get the latest CoyIM into buster-backports though. That would allow you to install it directly after adding the appropriate repository to your `/etc/apt/sources.list`. However, buster-backports is not open yet, so I ask for a little patience.
