### ISSUE TITLE
Be notified when you get to be a member (9.3)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#624]
When an administrator or owner grants you the member affiliation for a room, you should be notified of this. Since it can happen either when you are in the room, or when you're outside the room, this story means creating two notifications - one standalone when you're not in the room, and another for when you're in the room. These should include the reason provided. The standalone notification might give the option of joining the room directly, as well.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by azlancpool** [comment]
`user-test` was approved successful, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Lots of things to still fix.

**Comment by azlancpool** [comment]
In order to be more specific about the comments resolved, these are their links:
- https://github.com/coyim/coyim/commit/ee34f6a2159bebb30dfaf56bbc6adfa002cc9cce#r48055295
- https://github.com/coyim/coyim/commit/89c206142fc33c270758a13cfa8d11e295b26ebe#r48055834
- https://github.com/coyim/coyim/commit/89c206142fc33c270758a13cfa8d11e295b26ebe#r48056000
- https://github.com/coyim/coyim/commit/89c206142fc33c270758a13cfa8d11e295b26ebe#r48056009
- https://github.com/coyim/coyim/commit/89c206142fc33c270758a13cfa8d11e295b26ebe#r48056013
- https://github.com/coyim/coyim/commit/89c206142fc33c270758a13cfa8d11e295b26ebe#r48056040
- https://github.com/coyim/coyim/commit/89c206142fc33c270758a13cfa8d11e295b26ebe#r48056194
- https://github.com/coyim/coyim/commit/09e56b7bded708fbf21d9c7a90fa7c35abe3bcf5#r48056540
- https://github.com/coyim/coyim/commit/c8e3758bf1121de39f8c490d06fe87dc48b33fde#r48057223
- https://github.com/coyim/coyim/commit/f2d3d8c4da304a921680c1925ee35ee5cefcf1d6#r48057519
- https://github.com/coyim/coyim/commit/f2d3d8c4da304a921680c1925ee35ee5cefcf1d6#r48057524
- https://github.com/coyim/coyim/commit/4a37e23cc0be0f8804be1904750f6a21c9264a87#commitcomment-47996641
- https://github.com/coyim/coyim/commit/35898a80be642dbada4db248deb5eb819a2ec147#r48057649
- https://github.com/coyim/coyim/commit/c48c9120ae9299444a7671e0b11567adaa7eae91#r47905859
- https://github.com/coyim/coyim/commit/c48c9120ae9299444a7671e0b11567adaa7eae91#r47905865
- https://github.com/coyim/coyim/commit/c48c9120ae9299444a7671e0b11567adaa7eae91#r47905868
- https://github.com/coyim/coyim/commit/c48c9120ae9299444a7671e0b11567adaa7eae91#r47905870
- https://github.com/coyim/coyim/commit/c48c9120ae9299444a7671e0b11567adaa7eae91#r48057847
- https://github.com/coyim/coyim/commit/39dedcad18b39bde6d0f53ef63926b98aab47a6d#r48001989
- https://github.com/coyim/coyim/commit/df37e971fea33578a63d2c6944fd99811c073410#r47848660

So, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK
