### ISSUE TITLE
Revoke moderatorship to a moderator (9.7) (Optionally provide reason)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#634]
A moderator should be able to remove the moderator status for someone else. Since this is something that only happens in a room, this functionality should probably be possible to access from the user panel in the roster. Once you have chosen to change the role, you will be asked what the new role should be, and what the reason should be.

We might be able to unify these behaviors, since there are many different role-transition that a user can do to another user, we might do these as one piece of functionality, but it might also be clearer for a user to have specific actions. We should test and see what's better.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
Lots of things to fix.

**Comment by olabiniV2** [comment]
Hmm. There were many things to fix here, but I only see one fix in the commit attached. What about all the other things?

**Comment by azlancpool** [comment]
> Hmm. There were many things to fix here, but I only see one fix in the commit attached. What about all the other things?

Yep, It's because some comments was fixed through commits over other issues, so, We are mapping the fixes here.

**Comment by azlancpool** [comment]
In order to be more specific about the comments resolved, these are their links:
- https://github.com/coyim/coyim/commit/134d2f2bac5862c26901826536a9014ec667a588#r47810301
- https://github.com/coyim/coyim/commit/ec25fade94b7d9af9426a702ac7905996224a03c#r47810428
- https://github.com/coyim/coyim/commit/90a3a5555fbcb37149aa9d33095ddb902378204a#r47810665
- https://github.com/coyim/coyim/commit/aa5891b0ac7cc180cc454eac093db9039285ca25#r47810955

So, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK, still things to fix.

**Comment by azlancpool** [comment]
In order to be more specific about the comments resolved, these are their links:
- https://github.com/coyim/coyim/commit/365d2075eeebf106d07a9ee7da8498876106cead#r47889937
- https://github.com/coyim/coyim/commit/365d2075eeebf106d07a9ee7da8498876106cead#r47710333

So, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK, looks good!
