### ISSUE TITLE
Be notified of success or failure of the owner revocation (10.4)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#646]
When removing the owner status for a user, you should be told if the operation succeeded or failed, and if it failed, why it failed.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by azlancpool** [comment]
Changes related with user-test suggestions was done in 80e286c1cb6336c499872c191b1048c9be7b8bb7.
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Some things to fix.

**Comment by azlancpool** [comment]
In order to be more specific about the comments resolved, these are their links:
Changes in commits reviewed (ok)
- https://github.com/coyim/coyim/commit/b5f78ef18d65965c4952e389e820f5ae342160c4#r47315824
- https://github.com/coyim/coyim/commit/b18ded44cb9391af990e67c331ac3cbd9b7a24d8#r47850243
- https://github.com/coyim/coyim/commit/b18ded44cb9391af990e67c331ac3cbd9b7a24d8#r47315226
- https://github.com/coyim/coyim/commit/b18ded44cb9391af990e67c331ac3cbd9b7a24d8#r47315336
- https://github.com/coyim/coyim/commit/c31927c49fda46ed506b608c0644d358568b156f#r47854592
- https://github.com/coyim/coyim/commit/c31927c49fda46ed506b608c0644d358568b156f#r47854880

Commits to review
- https://github.com/coyim/coyim/commit/77d298f3d533df817a15025d422f1e4114788380#r47806616
- https://github.com/coyim/coyim/commit/77d298f3d533df817a15025d422f1e4114788380#r47810348


So, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK, this should be alright.
