### ISSUE TITLE
Be notified when you get to be an admin (10.6)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#651]
When adding the admin status to a user, you should be told if the operation succeeded or failed, and if it failed, why it failed.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment]
This is part of #271.

**Comment by olabiniV2** [comment]
There are some serious problems that need to be fixed. And more importantly, I can see that there's feedback from the user testing that hasn't been incorporated, so moving this to code review was incorrect to do in the first place.

**Comment by azlancpool** [comment]
`user-test` was approved successful, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
There are some things to fix here. But I also realized we have a problem with many of our i18n string - specifically the format ones that use more than one formatting expression. Imagine you have:
```
val := i18n.Localf("%s hello %s", 1, 2)
```
Imagine that another language requires a structure where the `2` would come before `1`. That's real problem with our current structure, since the formatting specifiers are in order. There's no way for a translation to change the order. I think we should change over to using indexed formatting strings in every call to `Localf`:
```
val := i18n.Localf("%[1]s hello %[2]s", 1, 2)
```

This way a translation string of `"%[2]s bla %[1]s"` could be possible.

**Comment by azlancpool** [comment]
This issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK
