### ISSUE TITLE
Pressing "ENTER" in the MUC windows should execute the default action of every form

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#673]

**Comment by peterpalau** [comment]
Ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Overall, I feel quite uncomfortable with a lot of the changes tagged with this issue - specifically because I have no idea what they have to do with the issue in question. I was thinking at several times that maybe the committers made a mistake by tagging this issue on all of these commits, or something like that.
We should be more careful.

**Comment by azlancpool** [comment]
Some comments related to the bad way to tag the commits wasn't replied because we accord a better way to do this. So, other comments were done and this issue is ready to code review by @olabiniV2

**Comment by olabiniV2** [comment]
OK, one method name to fix before this is done.

**Comment by peterpalau** [comment]
Okay we updated the method name in the last commit.

**Comment by olabiniV2** [comment]
Looks good to me.

**Comment by MauroVelasco** [comment]
Okay this issue is ready to be closed.
