### ISSUE TITLE
Add validations related with role and affiliation privileges 

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#687]

**Comment by azlancpool** [comment]
A small validation to add

**Comment by azlancpool** [comment]
Few improves after the user test are done, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Lots of things to fix.

**Comment by azlancpool** [comment]
In order to be more specific about the comments resolved, these are their links:
- https://github.com/coyim/coyim/commit/f1135872534b363431c3e7a5b16049ae9ad30e4b#r47859581
- https://github.com/coyim/coyim/commit/080f31ffec8c05845f191fff584c36c222bc50bb#r47859852
- https://github.com/coyim/coyim/commit/080f31ffec8c05845f191fff584c36c222bc50bb#r47860337
- https://github.com/coyim/coyim/commit/080f31ffec8c05845f191fff584c36c222bc50bb#r47860586
- https://github.com/coyim/coyim/commit/07b6eb98242bf55659bc285787fca6cb7a9dd5d4#r47895788
- https://github.com/coyim/coyim/commit/77d298f3d533df817a15025d422f1e4114788380#r47806616
- https://github.com/coyim/coyim/commit/77d298f3d533df817a15025d422f1e4114788380#r47810348
- https://github.com/coyim/coyim/commit/3c8f29312c94a2d1032faf0266dea67864e2aa7a#r47888822
- https://github.com/coyim/coyim/commit/ac9186b66ea59d783e7ca2c2ebad3c493ef8f2fe#r47896587
- https://github.com/coyim/coyim/commit/ac9186b66ea59d783e7ca2c2ebad3c493ef8f2fe#r47899545
- https://github.com/coyim/coyim/commit/ac9186b66ea59d783e7ca2c2ebad3c493ef8f2fe#r47899765
- https://github.com/coyim/coyim/commit/773b477c2655f515cf8231c788145fd5144ea15f#r47900577
- https://github.com/coyim/coyim/commit/773b477c2655f515cf8231c788145fd5144ea15f#r47900584
- https://github.com/coyim/coyim/commit/f2399d8ba635058722af58c82c25f4662a765ccc#r47900966
- https://github.com/coyim/coyim/commit/f438428404f8594f3ede41f38c7b661471eb6f3c#r47901504
- https://github.com/coyim/coyim/commit/3a4f52fc12963b9dabafb40a8f9bad926dbe5314#r47901693
- https://github.com/coyim/coyim/commit/3a4f52fc12963b9dabafb40a8f9bad926dbe5314#r47901695
- https://github.com/coyim/coyim/commit/bfac251cab9e69cc4093fa0a858325b6d4624d80#r47901816
- https://github.com/coyim/coyim/commit/a183c53f91217afcfcf68559a5f8d2e7fc7a75dc#r47811061
- https://github.com/coyim/coyim/commit/0f0713eead8ff9c2f56065bf31509572d5ab036e#r47710289
- https://github.com/coyim/coyim/commit/365d2075eeebf106d07a9ee7da8498876106cead#r47710333
- https://github.com/coyim/coyim/commit/365d2075eeebf106d07a9ee7da8498876106cead#r47889937
- https://github.com/coyim/coyim/commit/ee3d01effa9f51870a23e10991b766c21fd07305#r47800983

So, it's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Still lots to fix here.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by azlancpool** [comment]
It's ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment]
OK

**Comment by azlancpool** [comment]
A comment from the showcase needs to be done

**Comment by peterpalau** [comment]
I'm sorry, this issue should go first to user testing.
