### ISSUE TITLE
Failing Test_gajimImporter_TryImport_works

### ISSUE THREAD

**Issue by sacurio** [coyim/coyim#723]
The test is failing in Windows with the following output:

```
gajim_test.go:512:
    c.Assert(res, HasLen, 1)
... obtained []*config.ApplicationConfig = []*config.ApplicationConfig(nil)
... n int = 1
```

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
I had to comment out all the work you have done on this issue, because it doesn't even compile on other platforms than Windows...

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
Better, but still not enough. There are some problems - first, using set up and tear down of the suite is not appropriate, since the temp directory will be there the whole time during the full test run. Second, it will be using unnecessary stuff for the suite. You should consider creating a separate suite for only the tests that need it, instead of for all.

**Comment by peterpalau** [comment]
> Better, but still not enough. There are some problems - first, using set up and tear down of the suite is not appropriate, since the temp directory will be there the whole time during the full test run. Second, it will be using unnecessary stuff for the suite. You should consider creating a separate suite for only the tests that need it, instead of for all.

Interesting. Everything you suggest was our analysis but we wanted to know first if this was the way to do it. We are going to work on this .

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
OK, looks good.
