### ISSUE TITLE
Failing Test_resolve_handlesError

### ISSUE THREAD

**Issue by sacurio** [coyim/coyim#729]
The test is failing in Windows with the following output:

```
dns_test.go:64:
    //It only happens when using golang resolver
    //resolveSRVWithProxy will not return an error
    c.Assert(err, NotNil)
... value = nil
```

**Comment by peterpalau** [comment]
Okay, we're trying to understand this better, and we found that Go's default resolution implementation for doing a server lookup doesn't return any errors on Windows.

We also discovered that the function tested here is no longer used, perhaps because in the past it was decided to implement "our" resolver called `resolveSRVWithProxy`.

For that reason, we think it is better to remove the test and the functionality as they are no longer used in the code.

**Comment by olabiniV2** [comment]
All good to me.
