### ISSUE TITLE
Improve the appearance of the room view components within the global context.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#739]

**Comment by peterpalau** [comment]
Working on this issue, we realized that the changes that have been made in order to improve the visualization of the occupant info in the roster panel have affected the rest of the components inside the global view context of the room. 

We think the name of this issue should be updated in order to accomplish the fact that the roster panel must look good with the others components inside the room view.

**Comment by peterpalau** [comment]
This should go first to user testing in order to check if everything is good.

**Comment by peterpalau** [comment]
The user testing is done. The issue is ready to be reviewed.

**Comment by olabiniV2** [comment]
Things to fix.

**Comment by olabiniV2** [comment]
OK

**Comment by peterpalau** [comment]
This issue is done and ready to be closed.
