### ISSUE TITLE
Join Room ,  doesn't work when capital letter is entered in room field.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#741]

**Comment by peterpalau** [comment]
Based on the official RFC documentation for the `jid` syntax, the rules for `jid` are case insensitive. For that reason the service is failing when we try to join to a room using names like `rOom`, `Room` or `rooM`.

More information is available at:

- https://tools.ietf.org/html/rfc7622
- https://tools.ietf.org/html/rfc5234

**Comment by azlancpool** [comment]
In order to be more specific with the documentation related with this issue
>     * https://tools.ietf.org/html/rfc7622
https://tools.ietf.org/html/rfc7622#page-3 ->  `The syntax for a JID is defined as follows, using the Augmented
   Backus-Naur Form (ABNF) as specified in [RFC5234].`
>     * https://tools.ietf.org/html/rfc5234
https://tools.ietf.org/html/rfc5234#page-3 -> `Rule names are case insensitive`

**Comment by olabiniV2** [comment]
In theory, this is actually something that should happen on the server - failing to join should NOT depend on the case of the jid name, so any server that fails with different cases, is actually not compliant with XMPP. But this work around is fine for now  - although the assumption that the JIDs are lower case is a bit iffy.

**Comment by olabiniV2** [comment]
Reviewed, OK.
