### ISSUE TITLE
Handle re-connection to the room and add the new conversation history after reconnected.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#761]

**Comment by azlancpool** [comment]
Functionality is done, so it's ready to `user-test`

**Comment by azlancpool** [comment]
After `user-test` we need to work on:

- Do not clear notifications when connection is lost or recovered
 - Delete reconnecting notification when the reconnection process  finished
 - Use `left` and `joined` messages for `disconnect` and `reconnect` events in the conversation area

**Comment by azlancpool** [comment]
In the commit e2029c26 we removed functionality that clears all notifications, but in many places `clearErrors` method is called, which removes all notifications of  type `error`. This removes the disconnect notification.
We will implement an strategy to avoid this behaviour.

**Comment by azlancpool** [comment]
> After `user-test` we need to work on:
> 
>     * Do not clear notifications when connection is lost or recovered
> 
>     * Delete reconnecting notification when the reconnection process  finished
> 
>     * Use `left` and `joined` messages for `disconnect` and `reconnect` events in the conversation area

All these points are done, it's ready to `user-test`

**Comment by IvanJijon** [comment]
In user-test we decided to:

- Prevent to print more than once the message when a user loses connection

We also noticed that we needed to:
- Disable the edit subject components when a disconnect event is received
- Removes all "Connecting..." notifications because more than one could appear (e.g.: when the user loses connection to the server while reconnecting)

All these points have been treated in our previous commits: 
aae2480 236eaed 0dec19d 214a1f7

**Comment by olabiniV2** [comment]
OK
