### ISSUE TITLE
The notification messages shown to the user when their affiliation/role is changed are not showing in second person anymore

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#768]

**Comment by peterpalau** [comment]
We have tested with @sacurio all messages, and everything seems to work well.

**Comment by olabiniV2** [comment]
This one is very confusing. This was a bug that just changed what messages were being used, but it has a BUNCH of commits associated with it. Why?
Also, there seems to be open code review comments on this one, so not accepted.

**Comment by olabiniV2** [comment]
Still waiting for a response to the question in my comment...
Not accepted.

**Comment by azlancpool** [comment]
> This one is very confusing. This was a bug that just changed what messages were being used, but it has a BUNCH of commits associated with it. Why?

At the beginning of this issue, we realized that the logic behind the implementation at that time was in some way incomplete beacause the function `getMUCNotificationMessageFrom` should be the responsible to return the right message based on the given affiliation/role update type.

For that reason, we added custom data structures for `SelfAffiliationRoleUpdate` and `SelfRoleUpdate` that were missing and we added too the complete support for the events related to those structures. 

Another reason why we added more commits is because we did small visual updates related to the spacing and background of the notification component.

**Comment by azlancpool** [comment]
First we need to do user-test instead of code-review

**Comment by azlancpool** [comment]
After user tests, this must be done:
- Use always "expelled" instead of "temporarily removed" in messages like: The owner user1 `temporarily removed` user2 from the room.
- Remove highlights of "banned" and "expelled"/"temporarily removed" in notification messages. Only nicknames, affiliations and roles must have highlight in notification messages.

**Comment by azlancpool** [comment]
All user test comments have been solved

**Comment by olabiniV2** [comment]
OK
