### ISSUE TITLE
Remove focus from summary box items in the room configuration assistant.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#772]

**Comment by olabiniV2** [comment]
The problem here seems to be that the GTK assistant will, if an element has been used in any of the other pages, keep the focus in the page when you set a new one. This sometimes causes confusing behavior, including this one, and the one in #776. Basically, since the rows were the last things added, the focus jumps there. You can solve this, by making the ListBoxRows having `can-focus` set to `false`, but then the focus will jump to the label "Basic Information" about the list box. Not ideal.

This commit solves the problem by grabbing the focus and setting it in the navigation pane, after everything else is done. The current implementation does this by putting the function to achieve it in the UI thread queue to delay it a bit. A better strategy would be to refactor the whole configuration screen, to make it possible to expose hooks that can be called AFTER putting together the whole page and displaying it has been done. However, because of the current architecture that doesn't look very viable without a large amount of effort, so this workaround is used instead. As a side effect, the same fix solves #776 for the same reason - since the focus is taken away from items in the content pane.

**Comment by IvanJijon** [comment]
The commit b777a02 solves the problem for the configuration assistant, but the problem in the roster info pane remains.
To reproduce this behavior:

1. As an Owner or Administrator, access to an occupant's information in the roster of a room
2. Open the dialog to change the occupant's position by clicking in the position row
3. Cancel or close the window

You will see the focus remains in the previously clicked row.

**Comment by olabiniV2** [comment]
Sorry, I'm confused. What behavior in the roster info pane? I never saw that behavior.

**Comment by IvanJijon** [comment]
Following our conversation, this issue was reviewed with the team and we all agreed that the scope should only be the configuration assistant. The issue's title was updated.

**Comment by IvanJijon** [comment]
The implementation looks good.
