### ISSUE TITLE
No error reported when canceling config of a room and then trying to create room again

### ISSUE THREAD

**Issue by olabiniV2** [coyim/coyim#773]
If you follow these steps:
- `Chat Rooms` -> `Create Room`
- Enter a name for the room
- Choose a server
- Choose `Add custom room configuration`
- Press `Configure Room`
- Press `Cancel`
- Press `Configure Room` again

At this point, an error happens. Another story will be created to manage that. However, the problem here, is that the error is NOT made visible to the end user. Instead, nothing happens, no indication of a problem, but the create room dialog stays.

**Comment by IvanJijon** [comment]
We reproduced this issue only in our Prosody server, this doesn't occur with our e-jabberd server. The error received doesn't provide enough information useful for the user.
The error stanza received is:
```
<error type="cancel">
   <gone xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">xmpp:%!s(&lt;nil&gt;)?join</gone>
</error>
```
When this arrives, a generic error is shown to the user (handled in e9321e1). In order to provide more information to the user we could identify an error with `type="cancel"` that contains a `gone` tab inside and show a notification with the following message:
"The server couldn't create a room with the provided name. Please, change it and try again."

**Comment by azlancpool** [comment]
![imagen](https://user-images.githubusercontent.com/18559876/131888444-2d53e2c6-0ab9-49e8-819f-87d265c77fd2.png)

**Comment by azlancpool** [comment]
![imagen](https://user-images.githubusercontent.com/18559876/131889476-bae11f76-2b8e-4c79-b5cf-25b77360b396.png)

**Comment by azlancpool** [comment]
`user-test` requirements are met

**Comment by olabiniV2** [comment]
OK
