### ISSUE TITLE
Canceling configuring a room generates an error

### ISSUE THREAD

**Issue by olabiniV2** [coyim/coyim#781]
If you try to create a configured room, and then press cancel in the configuration assistant, you will see this error in the logs:
```
ERRO[0139] Trying to leave a room that is not present in the manager  account=olatest@testjabber.autonomia.digital component=session room=bbbb@conf.***.***.***
```

**Comment by sacurio** [comment]
We have found inside the current implementation some interesting logic that most of them don't make sense.

First, this error is shown during the destroy process because it assumes that the current room occupant is INSIDE (has joined) the room at the time the room configuration is canceled, or in other words, the room is destroyed. When we are creating a configured room, the self-occupant is NOT in the room until they join it.

Second, the function `m.roomManager.LeaveRoom` that removes the room with the given ID from the room manager, is a command, and as a command, it SHOULD not return anything. This is justified by the `CommandQuerySeparation` principle. In the current implementation, there are only two calls to this function. The first one, don't do anything with the return value, and the second call done by `deleteRoomFromManager`, is the one that prints the error log shown in the description of this issue. 

All the calls of `deleteRoomFromManager` have complete sense since they are made in contexts where the user is always in the room (user banned, user expelled and user removed because of a members-only room).

Third, having in consideration the current implementation for `m.roomManager.LeaveRoom`:

```golang
rm.lock.Lock()
defer rm.lock.Unlock()

_, ok := rm.rooms[room.String()]
if !ok {
  return false
}

delete(rm.rooms, room.String())
return true
```

We think a better solution or refactoring for this functionality would be as:

```golang
func (rm *RoomManager) LeaveRoom(room jid.Bare) {
  rm.lock.Lock()
  defer rm.lock.Unlock()

  delete(rm.rooms, room.String())
}
```

And last, the name `LeaveRoom` does not help in understanding the purpose of the method. For us, a better name would be `DeleteRoom` because that is what it's doing.

**Comment by sacurio** [comment]
> If you try to create a configured room, and then press cancel in the configuration assistant, you will see this error in the logs:
> 
> ```
> ERRO[0139] Trying to leave a room that is not present in the manager  account=olatest@testjabber.autonomia.digital component=session room=bbbb@conf.***.***.***
> ```

This error is the same that appears in the flow detailed on #774.

**Comment by azlancpool** [comment]
`user-test` was successful

**Comment by olabiniV2** [comment]
OK
