### ISSUE TITLE
macOS does not display the header titles (Name, ID, Description, Occupants) of the room list, when it is a public room.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#817]
This also happens in the list of pinned certificates, in the proxy list, and the import functionality. Further, it also happens in the standard Save/Load file dialog, which we use when sending/receiving files.

We have seen this behavior on Catalina and Big Sur. It works on one machine with Mojave, but it's unclear if this is a difference because of the version, or because I had the development environment installed on the Mojave machine.

**Comment by olabiniV2** [comment]
In order to debug this, we should try two things:

- [ ] Use another GTK program on the Big Sur machine, try to open a file and see if that works or not. Two possible alternatives would be one of the widget explorers, or Glade.
- [ ] Install the full development environment using Homebrew, and see if that changes the  behavior of the DMG
- [ ] Use the development environment to actually build a binary of Coy on the Mac, and see if that exhibits the same problem.

**Comment by olabiniV2** [comment]
We created a DMG that works on Mojave and ran the application there. However, this actually generated the same problems with the column headers as on Catalina and Big Sur. That means we can exclude the possibility that this is a compatibility problem in newer versions of GTK or OS X. Instead, the reason must be that we are missing some library in the DMG/.app

**Comment by olabiniV2** [comment]
GEdit was tested on Big Sur. The column titles are visible correctly in the file load/save dialogs there. This gives stronger evidence that we are simply missing the packaging of something.

**Comment by olabiniV2** [comment]
It turns out that the DMG script sets an environment variable to fix an issue in GDK rendering that was actually fixed in 2016. We simply remove this variable, and the column headers seem to work fine.

**Comment by azlancpool** [comment]
Reviewed by the team, OK
