### ISSUE TITLE
RFC 9266: Channel Bindings for TLS 1.3 support

### ISSUE THREAD

**Issue by Neustradamus** [coyim/coyim#847]
Can you add the support of RFC 9266: Channel Bindings for TLS 1.3?
- https://datatracker.ietf.org/doc/html/rfc9266

Little details, to know easily:
- tls-unique for TLS =< 1.2
- tls-server-end-point
- tls-exporter for TLS = 1.3

Thanks in advance.

Linked to:
- https://github.com/coyim/coyim/issues/536
- https://github.com/coyim/coyim/commit/872cc35d7f7ed80c143fb931915e6415512dc9a1
- https://github.com/coyim/coyim/commit/a91ae187324ecf7f4e2d6ed16337484c45eab57d
- https://github.com/coyim/coyim/pull/845

**Comment by olabiniV2** [comment]
Sorry for taking some time on this one. I have added some questions and comments in the PR - if you have answers, it would be useful.

**Comment by Neustradamus** [comment]
Dear @coyim team, @pedropalau, @olabini, @azlancpool, @juniorz, @sacurio, @MauroVelasco, @IvanJijon, @claucece, @olabiniV2, @tcz001, @rmendoza83, @tdruiva, @iapazmino, @giovaneliberato, @brl, @piratax007, @xSmurf, @varac, @tuliocasagrande, @reginazabo, @grayleonard, @unkaktus, @pixelrust, @PolarianDev, @comradekingu, @xmunoz, @haccer, @ageis, @silke, @satta, @jreyes33, @TheComputerCat, @Cris2760,

Can you look for Channel Binding for TLS 1.3 support?

There is a recent history with jabber.ru MITM and SCRAM-SHA-*-PLUS is the security solution!

Some sources about jabber.ru:
- https://notes.valdikss.org.ru/jabber.ru-mitm/
- https://snikket.org/blog/on-the-jabber-ru-mitm/
- https://www.devever.net/~hl/xmpp-incident
- https://blog.jmp.chat/b/certwatch

Thanks in advance.

Linked to:
- https://github.com/coyim/coyim/issues/862
- https://github.com/coyim/coyim/issues/863

**Comment by PolarianDev** [comment]
Hello,

Firstly it would be appreciated if you did not mention every single developer and contributor into your issue because of some fears about MitM, for example I have only contributed to the `README.md` because I adopted this package for Arch Linux, I have never contributed code, so mentioning me here was useless.

However I would like to point out that channel bindings is not the solution to every problem ever caused, you don't slap channel binding in and then the problem is fixed. Its a mitigation technique, it makes things harder, but not impossible, so this is not a "solution" but instead increasing resistance to MitM attacks. 

Finally, the MitM attack here is believed to be a lawful request by authorities, this is not a security vulnerability, at least from the software point of view, the cloud hosting providers own the network and hardware they provide you, they are more than able to intercept SSL certificates and packets on their network, or read the data on your server (such as yanking your certificates), and it being a lawful wiretap means they had the permission to do so. There is *NOTHING* you can do to prevent this.

This is a useful feature for strengthening the resistance to MitM attacks sure, but the real solution here is to always use E2E encryption, especially if you are on public XMPP servers, and if you are not? Self host your own and cut out the companies in the middle which could be compromised.

Take care,
Polarian

**Comment by olabiniV2** [comment]
@Neustradamus  - we consider this behavior abusive. This is our _only_ warning. Desist in abusive behavior, or you will be blocked and reported.

**Comment by olabiniV2** [comment]
@Neustradamus - As you are well aware, Golang still does not have proper support for `tls-exporter` channel binding. You know this since you have opened the issue in the Golang crypto issue tracker for this.

Second, the `jabber.ru` case has nothing to do with this - they were using valid certificates but different ones. Channel Binding for SCRAM would not have helped in that situation. However, pinning of certificates (which Coy already does) would actually help - and it's already there.

I will close this issue - there seems to be no movement on this front from the Golang side, and it is unclear whether the major XMPP servers have support for it anyway.

**Comment by Neustradamus** [comment]
Dear @olabiniV2, @Coyim team,

Thanks for your message.

First, I wish you a Happy New Year 2024 at all the team.

Second, I think it is not good to close unsolved ticket.

Third, @FiloSottile has said here: https://github.com/golang/go/issues/54103
```
Indeed, we already support EKM via ConnectionState.ExportKeyingMaterial.

What do you need us to change in crypto/tls?
```
Maybe you can talk with on the ticket about the situation?

Fourth point, for example:
- Jackal IM has the SCRAM-SHA-*-PLUS supports: https://github.com/ortuman/jackal/pull/243/files
- go-xmpp has the SCRAM-SHA-*-PLUS supports done by @mdosch: https://github.com/xmppo/go-xmpp/blob/master/xmpp.go
- go-sendxmpp has the SCRAM-SHA-*-PLUS supports done by @mdosch: https://salsa.debian.org/mdosch/go-sendxmpp

Thanks in advance.
