### ISSUE TITLE
Questions about Milestones

### ISSUE THREAD

**Issue by GreenLunar** [coyim/coyim#864]
Greetings,

I have read some of the tickets here and I would like to know what is the contribution policy conducted at CoyIM.

Specifically, I would like to know whether it would be worth to work on new features or improvements which function flawlessly and merge them into the project.

For example:
- Better VoIP.
- Extra VoIP features.
- More encryption systems.
- etc.

**Comment by olabiniV2** [comment]
Hi, 

Sorry for taking time to respond to this issue, and thank you for the interest.

In general, new features and improvements are definitely appreciated, however, they need to match with the focus of CoyIM, which is documented on the website: https://coy.im - specifically, we want to have as small an attack surface as possible. For those reasons, we have no planned to add neither VoIP nor other encryption features. We prefer to have one protocol that works well, rather than several.

Thanks

**Comment by GreenLunar** [comment]
I think your argument is indeed good, when a default is a consideration.

Had a plugin system be added, people would add extra features on their own.

CoyIM uses the (decentralized) XMPP protocol after all, and some organizations (companies and governments) would surely find a good use to it, as the XMPP protocol is prevalent, but the preferences and needs of different organizations may differ, and therefore, a plugin system would be a viable feature to implement.

Look at Gajim, as an example.
Gajim, which used to be an unstable software over a decade ago, and was lesser popular than Psi, has got very popular due to its better stability and also its plugin system which allowed to people to be free to add features that work for them.

Before the plugin system, the Gajim groupchat had 20 - 40 participants (and 70 at most), and today it has 300.

Do consider this.

**Comment by olabiniV2** [comment]
Well, we have actually considered it. On the same website I linked to earlier, it's explicitly described why a plugin system is a bad idea if you want a secure messenger. The reason why we felt CoyIM was necessary was because of the large attack surface of alternatives such as Gajim and Pidgin. A plugin system adds a lot of complexity and increases the attack surface - something that a secure messenger should not do.
